/// Flutter icons Whatsapp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Whatsapp
///      fonts:
///       - asset: fonts/Whatsapp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Whatsapp {
  Whatsapp._();

  static const _kFontFam = 'Whatsapp';
  static const String? _kFontPkg = null;

  static const IconData iconmonstr_whatsapp_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
